# Generated by Django 4.1.6 on 2023-02-09 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playerid', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=150)),
                ('score', models.IntegerField(default=0)),
                ('IsLevelFinished', models.BooleanField(default=False)),
                ('IsGameFinished', models.BooleanField(default=False)),
            ],
        ),
    ]
