# Generated by Django 4.1.6 on 2023-02-09 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scoreboard',
            name='id',
        ),
        migrations.AlterField(
            model_name='scoreboard',
            name='playerid',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
