# Generated by Django 4.1.6 on 2023-02-09 07:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0002_remove_scoreboard_id_alter_scoreboard_playerid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoreboard',
            name='playerid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
