# Generated by Django 4.1.6 on 2023-02-09 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0003_alter_scoreboard_playerid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoreboard',
            name='playerid',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
